org: sachinn
service: mikro-orm-postgres

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  deploymentBucket:
    name: workharu-serverless-deployment-ap-south-1
    serverSideEncryption: AES256
  environment:
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
  httpApi:
    cors: true

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: /
          method: POST
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /
          method: GET
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - .git/**
